image: docker:stable

services:
- docker:dind
<<<<<<< HEAD
=======

stages:
  - Build image and push
>>>>>>> bf8dda68c85865cf12d6571399f5a6f1e6efa2a2

stages:
  - Build image and push
  - Code quality test
docker build:
  stage: Build image and push
<<<<<<< HEAD
  script:
  - docker build -t aanjan1112/nodejs-frontend-client:v1 .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push aanjan1112/nodejs-frontend-client:v1

code_quality:
  stage: Code quality test
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
      paths: [gl-code-quality-report.json]

=======
  script:
  - docker build -t aanjan1112/nodejs-frontend-client:v1 .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push aanjan1112/nodejs-frontend-client:v1
  - echo "*************job done***********"
>>>>>>> bf8dda68c85865cf12d6571399f5a6f1e6efa2a2
